export const routineData = [
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Sun",
    time: "07:00 AM - 08:30 AM",
    type: "Lab",
    module: "Software Engineering",
    lecturer: "Mr. Ishan Singh Thakuri",
    block: "Skill",
    room: "Lab 11 - Dorjee Khando Lama",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Mon",
    time: "12:30 PM - 02:00 PM",
    type: "Lab",
    module: "Smart Data Discovery",
    lecturer: "Mr. Roshan Shrestha",
    block: "Skill",
    room: "Lab 05 - Pratima Giri",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Mon",
    time: "02:00 PM - 03:30 PM",
    type: "Lab",
    module: "Advanced Programming and Technologies",
    lecturer: "Ms. Katyani Bagjain",
    block: "Skill",
    room: "Lab 05 - Pratima Giri",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Tue",
    time: "07:00 AM - 08:30 AM",
    type: "Lecture",
    module: "Advanced Programming and Technologies",
    lecturer: "Mr. Prithivi Maharjan",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Tue",
    time: "10:00 AM - 11:30 AM",
    type: "Lecture",
    module: "Smart Data Discovery",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Wed",
    time: "11:30 AM - 01:00 PM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Wed",
    time: "01:00 PM - 02:00 PM",
    type: "Tutorial",
    module: "Smart Data Discovery",
    lecturer: "Mr. Roshan Shrestha",
    block: "Nepal",
    room: "TR03 - Pokhara",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Wed",
    time: "02:30 PM - 04:00 PM",
    type: "Lecture",
    module: "Professional and Ethical Issues",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Thu",
    time: "08:00 AM - 09:00 AM",
    type: "Tutorial",
    module: "Professional and Ethical Issues",
    lecturer: "Ms. Shreesha Rajbhandari",
    block: "Nepal",
    room: "TR03 - Pokhara",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Thu",
    time: "10:00 AM - 11:00 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Ishan Singh Thakuri",
    block: "Nepal",
    room: "TR04 - Lumbini",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Fri",
    time: "09:30 AM - 10:30 AM",
    type: "Tutorial",
    module: "Advanced Programming and Technologies",
    lecturer: "Ms. Katyani Bagjain",
    block: "Nepal",
    room: "TR04 - Lumbini",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Fri",
    time: "11:30 AM - 01:00 PM",
    type: "Lab",
    module: "Professional and Ethical Issues",
    lecturer: "Ms. Shreesha Rajbhandari",
    block: "Nepal",
    room: "TR04 - Lumbini",
  },
];

export const getSections = (year, faculty) => {
  const sections = {
    "Year 1": {
      Computing: ["-", "C11", "C12", "C13"],
      Networking: ["-", "N11", "N12"],
      AI: ["-", "AI11", "AI12"],
      Multimedia: ["-", "M11", "M12", "M13"],
    },
    "Year 2": {
      Computing: [
        "-",
        "C1",
        "C2",
        "C3",
        "C4",
        "C5",
        "C6",
        "C7",
        "C8",
        "C9",
        "C10",
        "C11",
        "C12",
        "C13",
        "C14",
        "C15",
        "C16",
        "C17",
        "C18",
      ],
      Networking: [
        "-",
        "N1",
        "N2",
        "N3",
        "N4",
        "N5",
        "N6",
        "N7",
        "N8",
        "N9",
        "N10",
        "N11",
      ],
      AI: ["-", "AI1", "AI2", "AI3", "AI4", "AI5", "AI6"],
      Multimedia: ["-", "M1", "M2", "M3", "M4", "M5", "M6"],
    },
    "Year 3": {
      Computing: ["-", "C31", "C32", "C33"],
      Networking: ["-", "N31", "N32"],
      AI: ["-", "AI31", "AI32"],
      Multimedia: ["-", "M31", "M32", "M33"],
    },
  };
  return sections[year]?.[faculty] || [];
};
