export const routineData = [
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Sun",
    time: "07:00 AM - 08:30 AM",
    type: "Lab",
    module: "Software Engineering",
    lecturer: "Mr. Ishan Singh Thakuri",
    block: "Skill",
    room: "Lab 11 - Dorjee Khando Lama",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Mon",
    time: "12:30 PM - 02:00 PM",
    type: "Lab",
    module: "Smart Data Discovery",
    lecturer: "Mr. Roshan Shrestha",
    block: "Skill",
    room: "Lab 05 - Pratima Giri",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Mon",
    time: "02:00 PM - 03:30 PM",
    type: "Lab",
    module: "Advanced Programming and Technologies",
    lecturer: "Ms. Katyani Bagjain",
    block: "Skill",
    room: "Lab 05 - Pratima Giri",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Tue",
    time: "07:00 AM - 08:30 AM",
    type: "Lecture",
    module: "Advanced Programming and Technologies",
    lecturer: "Mr. Prithivi Maharjan",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Tue",
    time: "10:00 AM - 11:30 AM",
    type: "Lecture",
    module: "Smart Data Discovery",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Wed",
    time: "11:30 AM - 01:00 PM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Wed",
    time: "01:00 PM - 02:00 PM",
    type: "Tutorial",
    module: "Smart Data Discovery",
    lecturer: "Mr. Roshan Shrestha",
    block: "Nepal",
    room: "TR03 - Pokhara",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Wed",
    time: "02:30 PM - 04:00 PM",
    type: "Lecture",
    module: "Professional and Ethical Issues",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Thu",
    time: "08:00 AM - 09:00 AM",
    type: "Tutorial",
    module: "Professional and Ethical Issues",
    lecturer: "Ms. Shreesha Rajbhandari",
    block: "Nepal",
    room: "TR03 - Pokhara",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Thu",
    time: "10:00 AM - 11:00 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Ishan Singh Thakuri",
    block: "Nepal",
    room: "TR04 - Lumbini",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Fri",
    time: "09:30 AM - 10:30 AM",
    type: "Tutorial",
    module: "Advanced Programming and Technologies",
    lecturer: "Ms. Katyani Bagjain",
    block: "Nepal",
    room: "TR04 - Lumbini",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Fri",
    time: "11:30 AM - 01:00 PM",
    type: "Lab",
    module: "Professional and Ethical Issues",
    lecturer: "Ms. Shreesha Rajbhandari",
    block: "Nepal",
    room: "TR04 - Lumbini",
  },
  {
    year: "Year 1",
    faculty: "Networking",
    section: "N9",
    batch: "Spring",
    day: "Sun",
    time: "10:00 AM - 11:30 AM",
    type: "Lecture",
    module: "Introduction to Networks",
    lecturer: "Mr. Prajjwal Paudyaraj",
    block: "Alumni",
    room: "LT06 - Chhinesh Lal Shrestha",
  },
  {
    year: "Year 1",
    faculty: "Networking",
    section: "N9",
    batch: "Spring",
    day: "Sun",
    time: "11:30 AM - 01:00 PM",
    type: "Lecture",
    module: "Cyber Security Fundamentals",
    lecturer: "Mr. Yuvraj Nepula",
    block: "Alumni",
    room: "LT06 - Chhinesh Lal Shrestha",
  },
  {
    year: "Year 1",
    faculty: "Networking",
    section: "N9",
    batch: "Spring",
    day: "Mon",
    time: "10:00 AM - 11:30 AM",
    type: "Lecture",
    module: "Programming",
    lecturer: "Mr. Ujjwal Adhikari",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 1",
    faculty: "Networking",
    section: "N9",
    batch: "Spring",
    day: "Mon",
    time: "12:00 PM - 01:00 PM",
    type: "Tutorial",
    module: "Cyber Security Fundamentals",
    lecturer: "Mr. Shailendra Singh Shahi",
    block: "Alumni",
    room: "SP08 - Satya Gurung",
  },
  {
    year: "Year 1",
    faculty: "Networking",
    section: "N9",
    batch: "Spring",
    day: "Mon",
    time: "01:00 PM - 02:30 PM",
    type: "Lecture",
    module: "Introduction to Information Systems",
    lecturer: "Mr. Hridaya Tandukar",
    block: "Kumari",
    room: "Hall - 02",
  },
  {
    year: "Year 1",
    faculty: "Networking",
    section: "N9",
    batch: "Spring",
    day: "Tue",
    time: "12:00 PM - 01:00 PM",
    type: "Tutorial",
    module: "Programming",
    lecturer: "Mr. Ujjwal Subedi",
    block: "Nepal",
    room: "TR03 - Pokhara",
  },
  {
    year: "Year 1",
    faculty: "Networking",
    section: "N9",
    batch: "Spring",
    day: "Tue",
    time: "02:00 PM - 03:30 PM",
    type: "Tutorial",
    module: "Introduction to Networks",
    lecturer: "Mr. Dhruva Pandey",
    block: "Alumni",
    room: "SR10 - Samir Gautam",
  },
  {
    year: "Year 1",
    faculty: "Networking",
    section: "N9",
    batch: "Spring",
    day: "Wed",
    time: "12:00 PM - 01:30 PM",
    type: "Lab",
    module: "Cyber Security Fundamentals",
    lecturer: "Mr. Shailendra Singh Shahi",
    block: "Skill",
    room: "Lab 10 - Pramod Deep Kamal",
  },
  {
    year: "Year 1",
    faculty: "Networking",
    section: "N9",
    batch: "Spring",
    day: "Wed",
    time: "02:00 PM - 03:00 PM",
    type: "Tutorial",
    module: "Introduction to Information Systems",
    lecturer: "Mr. Prajit Panta",
    block: "Nepal",
    room: "TR03 - Pokhara",
  },
  {
    year: "Year 1",
    faculty: "Networking",
    section: "N9",
    batch: "Spring",
    day: "Thu",
    time: "09:00 AM - 10:00 AM",
    type: "Lab",
    module: "Introduction to Networks",
    lecturer: "Mr. Dhruva Pandey",
    block: "Skill",
    room: "Lab 02 - Sanjay Lama",
  },
  {
    year: "Year 1",
    faculty: "Networking",
    section: "N9",
    batch: "Spring",
    day: "Thu",
    time: "10:00 AM - 11:30 AM",
    type: "Lab",
    module: "Programming",
    lecturer: "Mr. Ujjwal Subedi",
    block: "Skill",
    room: "Lab 03 - Sijan Ghimire",
  },
  {
    year: "Year 1",
    faculty: "Networking",
    section: "N9",
    batch: "Spring",
    day: "Fri",
    time: "07:00 AM - 08:30 AM",
    type: "Lab",
    module: "Introduction to Information Systems",
    lecturer: "Mr. Prajit Panta",
    block: "Skill",
    room: "Lab 07 - Rupesh Dangol",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Sun",
    time: "11:30 AM - 01:00 PM",
    type: "Lab",
    module: "Professional and Ethical Issues",
    lecturer: "Ms. Shresha Rajbhandari",
    block: "UK",
    room: "Lab - Newcastle",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Mon",
    time: "11:30 AM - 01:00 PM",
    type: "Lab",
    module: "Software Engineering",
    lecturer: "Mr. Ujal Bhatta",
    block: "Skill",
    room: "Lab 02 - Sangay Lama",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Tue",
    time: "07:00 AM - 08:30 AM",
    type: "Lecture",
    module: "Advanced Programming and Technologies",
    lecturer: "Mr. Prithivi Maharjan",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Tue",
    time: "10:00 AM - 11:30 AM",
    type: "Lecture",
    module: "Smart Data Discovery",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Wed",
    time: "11:30 AM - 01:00 PM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Wed",
    time: "01:00 PM - 02:00 PM",
    type: "Tutorial",
    module: "Advanced Programming and Technologies",
    lecturer: "Ms. Rabina Lama",
    block: "Alumni",
    room: "SR07 - Sujan Khadgi",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Wed",
    time: "02:30 PM - 04:00 PM",
    type: "Lecture",
    module: "Professional and Ethical Issues",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Thu",
    time: "11:00 AM - 12:00 PM",
    type: "Tutorial",
    module: "Professional and Ethical Issues",
    lecturer: "Ms. Shresha Rajbhandari",
    block: "Alumni",
    room: "LT08 - Naresh Lamgade",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Thu",
    time: "01:00 PM - 02:00 PM",
    type: "Tutorial",
    module: "Smart Data Discovery",
    lecturer: "Mr. Roshan Shrestha",
    block: "Nepal",
    room: "TR02 - Patan",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Thu",
    time: "02:00 PM - 03:30 PM",
    type: "Lab",
    module: "Advanced Programming and Technologies",
    lecturer: "Ms. Rabina Lama",
    block: "Skill",
    room: "Lab 01 - Sarun Dahal",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Fri",
    time: "08:30 AM - 10:00 AM",
    type: "Lab",
    module: "Smart Data Discovery",
    lecturer: "Mr. Roshan Shrestha",
    block: "Skill",
    room: "Lab 04 - Prajwol Adhikari",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Fri",
    time: "10:00 AM - 11:00 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Ujal Bhatta",
    block: "Nepal",
    room: "TR06 - Annapurna",
  },
];

export const getSections = (year, faculty, batch) => {
  const sections = {
    "Year 1": {
      Computing: {
        Autumn: ["-", "C11", "C12", "C13"],
        Spring: ["-", "C14", "C15", "C16"],
      },
      Networking: {
        Autumn: ["-", "N11", "N12"],
        Spring: ["-", "N9", "N10"],
      },
      AI: {
        Autumn: ["-", "AI11", "AI12"],
        Spring: ["-", "AI13", "AI14"],
      },
      Multimedia: {
        Autumn: ["-", "M11", "M12", "M13"],
        Spring: ["-", "M14", "M15"],
      },
    },
    "Year 2": {
      Computing: [
        "-",
        "C1",
        "C2",
        "C3",
        "C4",
        "C5",
        "C6",
        "C7",
        "C8",
        "C9",
        "C10",
        "C11",
        "C12",
        "C13",
        "C14",
        "C15",
        "C16",
        "C17",
        "C18",
      ],
      Networking: [
        "-",
        "N1",
        "N2",
        "N3",
        "N4",
        "N5",
        "N6",
        "N7",
        "N8",
        "N9",
        "N10",
        "N11",
      ],
      AI: ["-", "AI1", "AI2", "AI3", "AI4", "AI5", "AI6"],
      Multimedia: ["-", "M1", "M2", "M3", "M4", "M5", "M6"],
    },
    "Year 3": {
      Computing: ["-", "C31", "C32", "C33"],
      Networking: ["-", "N31", "N32"],
      AI: ["-", "AI31", "AI32"],
      Multimedia: ["-", "M31", "M32", "M33"],
    },
  };

  if (year === "Year 1" && batch) {
    return sections[year]?.[faculty]?.[batch] || [];
  }

  return sections[year]?.[faculty] || [];
};

export const getBatches = () => {
  return ["Autumn", "Spring"];
};
