import React, { useState, useEffect, useRef } from "react";
import { AiFillCaretDown } from "react-icons/ai";
import { FaChevronDown } from "react-icons/fa";

// Routine data
const routineData = [
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Sun",
    time: "07:00 AM - 08:30 AM",
    type: "Lab",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Ayush Bhakta Pradhanang",
    block: "UK",
    room: "Lab - Oxford",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C3",
    day: "Sun",
    time: "07:00 AM - 08:30 AM",
    type: "Lab",
    module: "Software Engineering",
    lecturer: "Mr. Mukesh Regmi",
    block: "UK",
    room: "Lab - Nottingham",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C9",
    day: "Sun",
    time: "07:30 AM - 09:00 AM",
    type: "Lab",
    module: "Software Engineering",
    lecturer: "Mr. Ujal Bhatta",
    block: "Alumni",
    room: "LT06 - Chhitesh Lal Shrestha",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C4",
    day: "Sun",
    time: "08:30 AM - 10:00 AM",
    type: "Lab",
    module: "Software Engineering",
    lecturer: "Mr. Mukesh Regmi",
    block: "UK",
    room: "Lab - Nottingham",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C1",
    day: "Sun",
    time: "09:00 AM - 10:30 AM",
    type: "Lab",
    module: "Databases",
    lecturer: "Ms. Astha Sharma",
    block: "Alumni",
    room: "LT06 - Chhitesh Lal Shrestha",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C2",
    day: "Sun",
    time: "09:00 AM - 10:30 AM",
    type: "Lab",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Skill Lab",
    room: "04 - Prajwol Adhikari",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Sun",
    time: "09:00 AM - 10:30 AM",
    type: "Lab",
    module: "Databases",
    lecturer: "Ms. Shresha Rajbhandari",
    block: "Alumni",
    room: "LT05 - Amir Khadka",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C5",
    day: "Sun",
    time: "09:00 AM - 10:30 AM",
    type: "Lab",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Ayush Bhakta Pradhanang",
    block: "London",
    room: "LT03 - Westminster Palace",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C15",
    day: "Sun",
    time: "10:00 AM - 11:30 AM",
    type: "Lab",
    module: "Software Engineering",
    lecturer: "Mr. Ishan Singh Thakuri",
    block: "London",
    room: "SR02 - Trafalgar Square",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C9",
    day: "Sun",
    time: "10:30 AM - 12:00 PM",
    type: "Lab",
    module: "Databases",
    lecturer: "Ms. Shresha Rajbhandari",
    block: "Alumni",
    room: "LT05 - Amir Khadka",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C2",
    day: "Sun",
    time: "10:30 AM - 12:00 PM",
    type: "Lab",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Skill Lab",
    room: "04 - Prajwol Adhikari",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C3",
    day: "Sun",
    time: "10:30 AM - 12:00 PM",
    type: "Lab",
    module: "Databases",
    lecturer: "Ms. Astha Sharma",
    block: "Alumni",
    room: "LT06 - Chhitesh Lal Shrestha",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C14",
    day: "Sun",
    time: "11:00 AM - 12:30 PM",
    type: "Lab",
    module: "Network Operating Systems",
    lecturer: "Mr. Rupsan Shrestha",
    block: "Skill Lab",
    room: "10 - Pranjal Deep Kanel",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Sun",
    time: "11:00 AM - 12:30 PM",
    type: "Lab",
    module: "Network Operating Systems",
    lecturer: "Mr. Bishnu Pandey",
    block: "Skill Lab",
    room: "11 - Dorjee Khando Lama",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C8",
    day: "Sun",
    time: "11:00 AM - 12:30 PM",
    type: "Lab",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Alumni",
    room: "SR10 - Samir Gautam",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C11",
    day: "Sun",
    time: "11:30 AM - 01:00 PM",
    type: "Lab",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Jaganath Paudyal",
    block: "Skill Lab",
    room: "08 - Vijay Pathak",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C16",
    day: "Sun",
    time: "11:30 AM - 01:00 PM",
    type: "Lab",
    module: "Software Engineering",
    lecturer: "Mr. Ishan Singh Thakuri",
    block: "London",
    room: "SR02 - Trafalgar Square",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C4",
    day: "Sun",
    time: "11:30 AM - 01:00 PM",
    type: "Lab",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Skill Lab",
    room: "07 - Rupesh Dangol",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C1",
    day: "Sun",
    time: "12:00 PM - 01:30 PM",
    type: "Lab",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Skill Lab",
    room: "04 - Prajwol Adhikari",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C15",
    day: "Sun",
    time: "12:30 PM - 02:00 PM",
    type: "Lab",
    module: "Network Operating Systems",
    lecturer: "Mr. Rupsan Shrestha",
    block: "Skill Lab",
    room: "10 - Pranjal Deep Kanel",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C8",
    day: "Sun",
    time: "12:30 PM - 02:00 PM",
    type: "Lab",
    module: "Network Operating Systems",
    lecturer: "Mr. Bishnu Pandey",
    block: "Skill Lab",
    room: "11 - Dorjee Khando Lama",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C7",
    day: "Sun",
    time: "01:00 PM - 02:30 PM",
    type: "Lab",
    module: "Software Engineering",
    lecturer: "Mr. Ujal Bhatta",
    block: "London",
    room: "SR01 - Tower Bridge",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Sun",
    time: "01:00 PM - 02:30 PM",
    type: "Lab",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Jaganath Paudyal",
    block: "Skill Lab",
    room: "08 - Vijay Pathak",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C17",
    day: "Sun",
    time: "01:00 PM - 02:30 PM",
    type: "Lab",
    module: "Software Engineering",
    lecturer: "Mr. Ishan Singh Thakuri",
    block: "London",
    room: "SR02 - Trafalgar Square",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C2",
    day: "Sun",
    time: "01:30 PM - 03:00 PM",
    type: "Lab",
    module: "Databases",
    lecturer: "Ms. Astha Sharma",
    block: "Alumni",
    room: "LT06 - Chhitesh Lal Shrestha",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C18",
    day: "Sun",
    time: "01:30 PM - 03:00 PM",
    type: "Lab",
    module: "Databases",
    lecturer: "Mr. Dipesh Raj Adhikari",
    block: "Alumni",
    room: "SR09 - Simran Bhattarai",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C11",
    day: "Sun",
    time: "01:30 PM - 03:00 PM",
    type: "Lab",
    module: "Databases",
    lecturer: "Ms. Shresha Rajbhandari",
    block: "Alumni",
    room: "LT05 - Amir Khadka",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C7",
    day: "Sun",
    time: "02:30 PM - 04:00 PM",
    type: "Lab",
    module: "Network Operating Systems",
    lecturer: "Mr. Bishnu Pandey",
    block: "Skill Lab",
    room: "11 - Dorjee Khando Lama",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C8",
    day: "Sun",
    time: "02:30 PM - 04:00 PM",
    type: "Lab",
    module: "Software Engineering",
    lecturer: "Mr. Ujal Bhatta",
    block: "London",
    room: "SR01 - Tower Bridge",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C13",
    day: "Sun",
    time: "02:30 PM - 04:00 PM",
    type: "Lab",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Jaganath Paudyal",
    block: "Skill Lab",
    room: "08 - Vijay Pathak",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C7",
    day: "Mon",
    time: "07:00 AM - 08:30 AM",
    type: "Lab",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Ayush Bhakta Pradhanang",
    block: "Skill Lab",
    room: "12 - Jagaran Maharjan",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C5",
    day: "Mon",
    time: "07:00 AM - 08:30 AM",
    type: "Lab",
    module: "Software Engineering",
    lecturer: "Mr. Mukesh Regmi",
    block: "Nepal",
    room: "TR04 - Lumbini",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C18",
    day: "Mon",
    time: "07:00 AM - 08:30 AM",
    type: "Lab",
    module: "Network Operating Systems",
    lecturer: "Mr. Rupsan Shrestha",
    block: "Nepal",
    room: "TR02 - Patan",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C13",
    day: "Mon",
    time: "07:30 AM - 09:00 AM",
    type: "Lab",
    module: "Databases",
    lecturer: "Ms. Shresha Rajbhandari",
    block: "London",
    room: "LT03 - Westminster Palace",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C6",
    day: "Mon",
    time: "08:30 AM - 10:00 AM",
    type: "Lab",
    module: "Software Engineering",
    lecturer: "Mr. Mukesh Regmi",
    block: "Nepal",
    room: "TR08 - Sagarmatha",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C17",
    day: "Mon",
    time: "09:00 AM - 10:30 AM",
    type: "Lab",
    module: "Network Operating Systems",
    lecturer: "Mr. Rupsan Shrestha",
    block: "Skill Lab",
    room: "01 - Sarun Dahal",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C9",
    day: "Mon",
    time: "09:00 AM - 10:30 AM",
    type: "Lab",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Ayush Bhakta Pradhanang",
    block: "Skill Lab",
    room: "04 - Prajwol Adhikari",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Mon",
    time: "10:00 AM - 11:30 AM",
    type: "Lab",
    module: "Software Engineering",
    lecturer: "Mr. Ujal Bhatta",
    block: "London",
    room: "SR02 - Trafalgar Square",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C5",
    day: "Mon",
    time: "10:00 AM - 11:30 AM",
    type: "Lab",
    module: "Databases",
    lecturer: "Ms. Astha Sharma",
    block: "London",
    room: "SR01 - Tower Bridge",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C18",
    day: "Mon",
    time: "10:00 AM - 11:30 AM",
    type: "Lab",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Jaganath Paudyal",
    block: "Skill Lab",
    room: "02 - Sangay Lama",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C14",
    day: "Mon",
    time: "10:30 AM - 12:00 PM",
    type: "Lab",
    module: "Databases",
    lecturer: "Ms. Shresha Rajbhandari",
    block: "Alumni",
    room: "LT04 - Tridev Gurung",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C16",
    day: "Mon",
    time: "10:30 AM - 12:00 PM",
    type: "Lab",
    module: "Databases",
    lecturer: "Mr. Dipesh Raj Adhikari",
    block: "Alumni",
    room: "LT08 - Naresh Lamgade",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C3",
    day: "Mon",
    time: "11:00 AM - 12:30 PM",
    type: "Lab",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Skill Lab",
    room: "03 - Srijan Ghimire",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C13",
    day: "Mon",
    time: "11:00 AM - 12:30 PM",
    type: "Lab",
    module: "Software Engineering",
    lecturer: "Mr. Ishan Singh Thakuri",
    block: "UK",
    room: "Lab - Oxford",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C11",
    day: "Mon",
    time: "11:30 AM - 01:00 PM",
    type: "Lab",
    module: "Software Engineering",
    lecturer: "Mr. Ujal Bhatta",
    block: "London",
    room: "SR02 - Trafalgar Square",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C9",
    day: "Mon",
    time: "11:30 AM - 01:00 PM",
    type: "Lab",
    module: "Network Operating Systems",
    lecturer: "Mr. Bishnu Pandey",
    block: "Skill Lab",
    room: "11 - Dorjee Khando Lama",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C6",
    day: "Mon",
    time: "11:30 AM - 01:00 PM",
    type: "Lab",
    module: "Databases",
    lecturer: "Ms. Astha Sharma",
    block: "London",
    room: "SR01 - Tower Bridge",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C1",
    day: "Mon",
    time: "12:00 PM - 01:30 PM",
    type: "Lab",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Skill Lab",
    room: "02 - Sangay Lama",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C14",
    day: "Mon",
    time: "12:00 PM - 01:30 PM",
    type: "Lab",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Jaganath Paudyal",
    block: "Skill Lab",
    room: "04 - Prajwol Adhikari",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C15",
    day: "Mon",
    time: "12:00 PM - 01:30 PM",
    type: "Lab",
    module: "Databases",
    lecturer: "Ms. Shresha Rajbhandari",
    block: "Alumni",
    room: "LT04 - Tridev Gurung",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C17",
    day: "Mon",
    time: "12:00 PM - 01:30 PM",
    type: "Lab",
    module: "Databases",
    lecturer: "Mr. Dipesh Raj Adhikari",
    block: "Alumni",
    room: "LT08 - Naresh Lamgade",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Mon",
    time: "12:30 PM - 02:00 PM",
    type: "Lab",
    module: "Software Engineering",
    lecturer: "Mr. Ishan Singh Thakuri",
    block: "UK",
    room: "Lab - Oxford",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C4",
    day: "Mon",
    time: "12:30 PM - 02:00 PM",
    type: "Lab",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Skill Lab",
    room: "03 - Srijan Ghimire",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Mon",
    time: "01:00 PM - 02:30 PM",
    type: "Lab",
    module: "Network Operating Systems",
    lecturer: "Mr. Bishnu Pandey",
    block: "Skill Lab",
    room: "11 - Dorjee Khando Lama",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C3",
    day: "Mon",
    time: "01:30 PM - 03:00 PM",
    type: "Lab",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Skill Lab",
    room: "02 - Sangay Lama",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C15",
    day: "Mon",
    time: "01:30 PM - 03:00 PM",
    type: "Lab",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Jaganath Paudyal",
    block: "Skill Lab",
    room: "06 - Anew Karki",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C14",
    day: "Mon",
    time: "02:00 PM - 03:30 PM",
    type: "Lab",
    module: "Software Engineering",
    lecturer: "Mr. Ishan Singh Thakuri",
    block: "UK",
    room: "Lab - Oxford",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C4",
    day: "Mon",
    time: "02:30 PM - 04:00 PM",
    type: "Lab",
    module: "Databases",
    lecturer: "Ms. Astha Sharma",
    block: "London",
    room: "SR03 - Piccadilly Circus",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Tue",
    time: "07:00 AM - 08:30 AM",
    type: "Lecture",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C11",
    day: "Tue",
    time: "07:00 AM - 08:30 AM",
    type: "Lecture",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Tue",
    time: "07:00 AM - 08:30 AM",
    type: "Lecture",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C13",
    day: "Tue",
    time: "07:00 AM - 08:30 AM",
    type: "Lecture",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C14",
    day: "Tue",
    time: "07:00 AM - 08:30 AM",
    type: "Lecture",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C15",
    day: "Tue",
    time: "07:00 AM - 08:30 AM",
    type: "Lecture",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C16",
    day: "Tue",
    time: "07:00 AM - 08:30 AM",
    type: "Lecture",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C17",
    day: "Tue",
    time: "07:00 AM - 08:30 AM",
    type: "Lecture",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C18",
    day: "Tue",
    time: "07:00 AM - 08:30 AM",
    type: "Lecture",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Tue",
    time: "08:30 AM - 10:00 AM",
    type: "Lecture",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C11",
    day: "Tue",
    time: "08:30 AM - 10:00 AM",
    type: "Lecture",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Tue",
    time: "08:30 AM - 10:00 AM",
    type: "Lecture",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C13",
    day: "Tue",
    time: "08:30 AM - 10:00 AM",
    type: "Lecture",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C14",
    day: "Tue",
    time: "08:30 AM - 10:00 AM",
    type: "Lecture",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C15",
    day: "Tue",
    time: "08:30 AM - 10:00 AM",
    type: "Lecture",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C16",
    day: "Tue",
    time: "08:30 AM - 10:00 AM",
    type: "Lecture",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C17",
    day: "Tue",
    time: "08:30 AM - 10:00 AM",
    type: "Lecture",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C18",
    day: "Tue",
    time: "08:30 AM - 10:00 AM",
    type: "Lecture",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C1",
    day: "Tue",
    time: "10:00 AM - 11:30 AM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C2",
    day: "Tue",
    time: "10:00 AM - 11:30 AM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C3",
    day: "Tue",
    time: "10:00 AM - 11:30 AM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C4",
    day: "Tue",
    time: "10:00 AM - 11:30 AM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C5",
    day: "Tue",
    time: "10:00 AM - 11:30 AM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C6",
    day: "Tue",
    time: "10:00 AM - 11:30 AM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C7",
    day: "Tue",
    time: "10:00 AM - 11:30 AM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C8",
    day: "Tue",
    time: "10:00 AM - 11:30 AM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C9",
    day: "Tue",
    time: "10:00 AM - 11:30 AM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C1",
    day: "Tue",
    time: "01:00 PM - 02:30 PM",
    type: "Lecture",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C2",
    day: "Tue",
    time: "01:00 PM - 02:30 PM",
    type: "Lecture",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C3",
    day: "Tue",
    time: "01:00 PM - 02:30 PM",
    type: "Lecture",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C4",
    day: "Tue",
    time: "01:00 PM - 02:30 PM",
    type: "Lecture",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C5",
    day: "Tue",
    time: "01:00 PM - 02:30 PM",
    type: "Lecture",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C6",
    day: "Tue",
    time: "01:00 PM - 02:30 PM",
    type: "Lecture",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C7",
    day: "Tue",
    time: "01:00 PM - 02:30 PM",
    type: "Lecture",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C8",
    day: "Tue",
    time: "01:00 PM - 02:30 PM",
    type: "Lecture",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C9",
    day: "Tue",
    time: "01:00 PM - 02:30 PM",
    type: "Lecture",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C1",
    day: "Tue",
    time: "02:30 PM - 04:00 PM",
    type: "Lecture",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C2",
    day: "Tue",
    time: "02:30 PM - 04:00 PM",
    type: "Lecture",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C3",
    day: "Tue",
    time: "02:30 PM - 04:00 PM",
    type: "Lecture",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C4",
    day: "Tue",
    time: "02:30 PM - 04:00 PM",
    type: "Lecture",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C5",
    day: "Tue",
    time: "02:30 PM - 04:00 PM",
    type: "Lecture",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C6",
    day: "Tue",
    time: "02:30 PM - 04:00 PM",
    type: "Lecture",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C7",
    day: "Tue",
    time: "02:30 PM - 04:00 PM",
    type: "Lecture",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C8",
    day: "Tue",
    time: "02:30 PM - 04:00 PM",
    type: "Lecture",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C9",
    day: "Tue",
    time: "02:30 PM - 04:00 PM",
    type: "Lecture",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C6",
    day: "Wed",
    time: "07:00 AM - 08:00 AM",
    type: "Tutorial",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Ayush Bhakta Pradhanang",
    block: "Alumni",
    room: "LT04 - Tridev Gurung",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C9",
    day: "Wed",
    time: "07:00 AM - 08:00 AM",
    type: "Tutorial",
    module: "Network Operating Systems",
    lecturer: "Mr. Bishnu Pandey",
    block: "London",
    room: "LT01 - Buckingham Palace",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C4",
    day: "Wed",
    time: "07:00 AM - 08:00 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Mukesh Regmi",
    block: "Nepal",
    room: "TR07 - Kanchanjunga",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C14",
    day: "Wed",
    time: "09:00 AM - 10:00 AM",
    type: "Tutorial",
    module: "Network Operating Systems",
    lecturer: "Mr. Rupsan Shrestha",
    block: "Alumni",
    room: "LT08 - Naresh Lamgade",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Wed",
    time: "09:00 AM - 10:00 AM",
    type: "Tutorial",
    module: "Network Operating Systems",
    lecturer: "Mr. Bishnu Pandey",
    block: "Alumni",
    room: "SR08 - Sajiya Gurung",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C16",
    day: "Wed",
    time: "09:00 AM - 10:00 AM",
    type: "Tutorial",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Jaganath Paudyal",
    block: "London",
    room: "SR03 - Piccadilly Circus",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C13",
    day: "Wed",
    time: "10:00 AM - 11:00 AM",
    type: "Tutorial",
    module: "Network Operating Systems",
    lecturer: "Mr. Rupsan Shrestha",
    block: "Alumni",
    room: "LT05 - Amir Khadka",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C3",
    day: "Wed",
    time: "10:00 AM - 11:00 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Mukesh Regmi",
    block: "London",
    room: "SR03 - Piccadilly Circus",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C8",
    day: "Wed",
    time: "10:00 AM - 11:00 AM",
    type: "Tutorial",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Ayush Bhakta Pradhanang",
    block: "Alumni",
    room: "LT06 - Chhitesh Lal Shrestha",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C17",
    day: "Wed",
    time: "10:00 AM - 11:00 AM",
    type: "Tutorial",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Jaganath Paudyal",
    block: "London",
    room: "LT03 - Westminster Palace",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Wed",
    time: "10:00 AM - 11:00 AM",
    type: "Tutorial",
    module: "Network Operating Systems",
    lecturer: "Mr. Bishnu Pandey",
    block: "Alumni",
    room: "SR08 - Sajiya Gurung",
  },

  // Lectures
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C1",
    day: "Wed",
    time: "08:30 AM - 10:00 AM",
    type: "Lecture",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C2",
    day: "Wed",
    time: "08:30 AM - 10:00 AM",
    type: "Lecture",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C3",
    day: "Wed",
    time: "08:30 AM - 10:00 AM",
    type: "Lecture",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C4",
    day: "Wed",
    time: "08:30 AM - 10:00 AM",
    type: "Lecture",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C5",
    day: "Wed",
    time: "08:30 AM - 10:00 AM",
    type: "Lecture",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C6",
    day: "Wed",
    time: "08:30 AM - 10:00 AM",
    type: "Lecture",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C7",
    day: "Wed",
    time: "08:30 AM - 10:00 AM",
    type: "Lecture",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C8",
    day: "Wed",
    time: "08:30 AM - 10:00 AM",
    type: "Lecture",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C9",
    day: "Wed",
    time: "08:30 AM - 10:00 AM",
    type: "Lecture",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Wed",
    time: "11:30 AM - 01:00 PM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C11",
    day: "Wed",
    time: "11:30 AM - 01:00 PM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Wed",
    time: "11:30 AM - 01:00 PM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C13",
    day: "Wed",
    time: "11:30 AM - 01:00 PM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C14",
    day: "Wed",
    time: "11:30 AM - 01:00 PM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C15",
    day: "Wed",
    time: "11:30 AM - 01:00 PM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C16",
    day: "Wed",
    time: "11:30 AM - 01:00 PM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C17",
    day: "Wed",
    time: "11:30 AM - 01:00 PM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C18",
    day: "Wed",
    time: "11:30 AM - 01:00 PM",
    type: "Lecture",
    module: "Software Engineering",
    lecturer: "Mr. Rubin Thapa",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Wed",
    time: "01:00 PM - 02:30 PM",
    type: "Lecture",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C11",
    day: "Wed",
    time: "01:00 PM - 02:30 PM",
    type: "Lecture",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Wed",
    time: "01:00 PM - 02:30 PM",
    type: "Lecture",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C13",
    day: "Wed",
    time: "01:00 PM - 02:30 PM",
    type: "Lecture",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C14",
    day: "Wed",
    time: "01:00 PM - 02:30 PM",
    type: "Lecture",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C15",
    day: "Wed",
    time: "01:00 PM - 02:30 PM",
    type: "Lecture",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C16",
    day: "Wed",
    time: "01:00 PM - 02:30 PM",
    type: "Lecture",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C17",
    day: "Wed",
    time: "01:00 PM - 02:30 PM",
    type: "Lecture",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C18",
    day: "Wed",
    time: "01:00 PM - 02:30 PM",
    type: "Lecture",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Kumari",
    room: "Hall - 01",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C11",
    day: "Wed",
    time: "02:30 PM - 03:30 PM",
    type: "Tutorial",
    module: "Network Operating Systems",
    lecturer: "Mr. Bishnu Pandey",
    block: "Alumni",
    room: "SR06 - Abhash Bikram Thapa",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C9",
    day: "Thu",
    time: "07:00 AM - 08:00 AM",
    type: "Tutorial",
    module: "Databases",
    lecturer: "Ms. Shresha Rajbhandari",
    block: "UK",
    room: "Lab - Oxford",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C11",
    day: "Thu",
    time: "07:00 AM - 08:00 AM",
    type: "Tutorial",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Jaganath Paudyal",
    block: "London",
    room: "SR01 - Tower Bridge",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C15",
    day: "Thu",
    time: "07:00 AM - 08:00 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Ishan Singh Thakuri",
    block: "London",
    room: "LT03 - Westminster Palace",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C6",
    day: "Thu",
    time: "07:00 AM - 08:00 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Mukesh Regmi",
    block: "Alumni",
    room: "LT04 - Tridev Gurung",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C16",
    day: "Thu",
    time: "07:00 AM - 08:00 AM",
    type: "Tutorial",
    module: "Network Operating Systems",
    lecturer: "Mr. Rupsan Shrestha",
    block: "Alumni",
    room: "LT05 - Amir Khadka",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Thu",
    time: "08:00 AM - 09:00 AM",
    type: "Tutorial",
    module: "Databases",
    lecturer: "Ms. Shresha Rajbhandari",
    block: "UK",
    room: "Lab - Oxford",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Thu",
    time: "08:00 AM - 09:00 AM",
    type: "Tutorial",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Jaganath Paudyal",
    block: "London",
    room: "SR01 - Tower Bridge",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C5",
    day: "Thu",
    time: "08:00 AM - 09:00 AM",
    type: "Tutorial",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Ayush Bhakta Pradhanang",
    block: "London",
    room: "LT03 - Westminster Palace",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C1",
    day: "Thu",
    time: "08:00 AM - 09:00 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Mukesh Regmi",
    block: "Alumni",
    room: "LT04 - Tridev Gurung",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C17",
    day: "Thu",
    time: "08:00 AM - 09:00 AM",
    type: "Tutorial",
    module: "Network Operating Systems",
    lecturer: "Mr. Rupsan Shrestha",
    block: "Alumni",
    room: "LT05 - Amir Khadka",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C9",
    day: "Thu",
    time: "08:30 AM - 09:30 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Ujal Bhatta",
    block: "Alumni",
    room: "LT06 - Chhitesh Lal Shrestha",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C6",
    day: "Thu",
    time: "08:30 AM - 09:30 AM",
    type: "Tutorial",
    module: "Network Operating Systems",
    lecturer: "Mr. Bishnu Pandey",
    block: "Alumni",
    room: "LT08 - Naresh Lamgade",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C16",
    day: "Thu",
    time: "09:00 AM - 10:00 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Ishan Singh Thakuri",
    block: "UK",
    room: "Lab - Newcastle",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C4",
    day: "Thu",
    time: "09:00 AM - 10:00 AM",
    type: "Tutorial",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "UK",
    room: "Lab - Nottingham",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C11",
    day: "Thu",
    time: "09:00 AM - 10:00 AM",
    type: "Tutorial",
    module: "Databases",
    lecturer: "Ms. Shresha Rajbhandari",
    block: "UK",
    room: "Lab - Oxford",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Thu",
    time: "09:00 AM - 10:00 AM",
    type: "Tutorial",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Ayush Bhakta Pradhanang",
    block: "London",
    room: "LT03 - Westminster Palace",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C2",
    day: "Thu",
    time: "09:00 AM - 10:00 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Mukesh Regmi",
    block: "Alumni",
    room: "LT04 - Tridev Gurung",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C18",
    day: "Thu",
    time: "09:00 AM - 10:00 AM",
    type: "Tutorial",
    module: "Network Operating Systems",
    lecturer: "Mr. Rupsan Shrestha",
    block: "Alumni",
    room: "LT05 - Amir Khadka",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C1",
    day: "Thu",
    time: "09:00 AM - 10:00 AM",
    type: "Tutorial",
    module: "Databases",
    lecturer: "Ms. Astha Sharma",
    block: "Alumni",
    room: "SR05 - Rotash Shrestha",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C8",
    day: "Thu",
    time: "09:00 AM - 10:00 AM",
    type: "Tutorial",
    module: "Databases",
    lecturer: "Mr. Aadesh Tandukar",
    block: "Nepal",
    room: "TR06 - Annapurna",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C7",
    day: "Thu",
    time: "09:30 AM - 10:30 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Ujal Bhatta",
    block: "Alumni",
    room: "LT06 - Chhitesh Lal Shrestha",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C5",
    day: "Thu",
    time: "09:30 AM - 10:30 AM",
    type: "Tutorial",
    module: "Network Operating Systems",
    lecturer: "Mr. Bishnu Pandey",
    block: "Alumni",
    room: "LT08 - Naresh Lamgade",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C17",
    day: "Thu",
    time: "10:00 AM - 11:00 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Ishan Singh Thakuri",
    block: "UK",
    room: "Lab - Newcastle",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Thu",
    time: "10:00 AM - 11:00 AM",
    type: "Tutorial",
    module: "Databases",
    lecturer: "Ms. Shresha Rajbhandari",
    block: "UK",
    room: "Lab - Oxford",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C6",
    day: "Thu",
    time: "10:00 AM - 11:30 AM",
    type: "Lab",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Ayush Bhakta Pradhanang",
    block: "Skill Lab",
    room: "01 - Sarun Dahal",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C16",
    day: "Thu",
    time: "10:00 AM - 11:30 AM",
    type: "Lab",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Jaganath Paudyal",
    block: "Skill Lab",
    room: "04 - Prajwol Adhikari",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C2",
    day: "Thu",
    time: "10:00 AM - 11:00 AM",
    type: "Tutorial",
    module: "Databases",
    lecturer: "Ms. Astha Sharma",
    block: "Alumni",
    room: "SR05 - Rotash Shrestha",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C1",
    day: "Thu",
    time: "10:00 AM - 11:00 AM",
    type: "Tutorial",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Alumni",
    room: "SR10 - Samir Gautam",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C8",
    day: "Thu",
    time: "10:30 AM - 11:30 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Ujal Bhatta",
    block: "Alumni",
    room: "LT06 - Chhitesh Lal Shrestha",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C2",
    day: "Thu",
    time: "11:00 AM - 12:00 PM",
    type: "Tutorial",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Alumni",
    room: "SR10 - Samir Gautam",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C18",
    day: "Thu",
    time: "11:00 AM - 12:00 PM",
    type: "Tutorial",
    module: "Databases",
    lecturer: "Mr. Dipesh Raj Adhikari",
    block: "Nepal",
    room: "TR03 - Pokhara",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C8",
    day: "Thu",
    time: "11:30 AM - 12:30 PM",
    type: "Tutorial",
    module: "Network Operating Systems",
    lecturer: "Mr. Bishnu Pandey",
    block: "Alumni",
    room: "LT08 - Naresh Lamgade",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C7",
    day: "Thu",
    time: "12:00 PM - 01:00 PM",
    type: "Tutorial",
    module: "Databases",
    lecturer: "Ms. Astha Sharma",
    block: "Alumni",
    room: "SR05 - Rotash Shrestha",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C3",
    day: "Thu",
    time: "12:00 PM - 01:00 PM",
    type: "Tutorial",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Alumni",
    room: "SR06 - Abhash Bikram Thapa",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C18",
    day: "Thu",
    time: "12:00 PM - 01:00 PM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Ishan Singh Thakuri",
    block: "Nepal",
    room: "TR03 - Pokhara",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C13",
    day: "Thu",
    time: "01:00 PM - 02:00 PM",
    type: "Tutorial",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Jaganath Paudyal",
    block: "Nepal",
    room: "TR01 - Kantipur",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C7",
    day: "Thu",
    time: "01:00 PM - 02:00 PM",
    type: "Tutorial",
    module: "Network Operating Systems",
    lecturer: "Mr. Bishnu Pandey",
    block: "Alumni",
    room: "SR06 - Abhash Bikram Thapa",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C3",
    day: "Thu",
    time: "02:00 PM - 03:00 PM",
    type: "Tutorial",
    module: "Databases",
    lecturer: "Ms. Astha Sharma",
    block: "Alumni",
    room: "SR06 - Abhash Bikram Thapa",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C13",
    day: "Fri",
    time: "07:00 AM - 08:00 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Ishan Singh Thakuri",
    block: "Nepal",
    room: "TR06 - Annapurna",
  },
  {
    year: "Year 2",
    faculty: "Networking",
    section: "C11",
    day: "Fri",
    time: "07:00 AM - 08:30 AM",
    type: "Lab",
    module: "Network Operating Systems",
    lecturer: "Mr. Bishnu Pandey",
    block: "Skill Lab",
    room: "01 - Sarun Dahal",
  },
  {
    year: "Year 2",
    faculty: "Networking",
    section: "C16",
    day: "Fri",
    time: "07:00 AM - 08:30 AM",
    type: "Lab",
    module: "Network Operating Systems",
    lecturer: "Mr. Rupsan Shrestha",
    block: "Skill Lab",
    room: "04 - Prajwol Adhikari",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C8",
    day: "Fri",
    time: "07:00 AM - 08:30 AM",
    type: "Lab",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Ayush Bhakta Pradhanang",
    block: "Skill Lab",
    room: "08 - Vijay Pathak",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C10",
    day: "Fri",
    time: "07:00 AM - 08:00 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Ujal Bhatta",
    block: "Alumni",
    room: "SR07 - Sujan Khadgi",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C1",
    day: "Fri",
    time: "07:00 AM - 08:00 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Mukesh Regmi",
    block: "Alumni",
    room: "SR09 - Simran Bhattarai",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C5",
    day: "Fri",
    time: "08:00 AM - 09:00 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Mukesh Regmi",
    block: "London",
    room: "SR01 - Tower Bridge",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C7",
    day: "Fri",
    time: "08:00 AM - 09:00 AM",
    type: "Lab",
    module: "Databases",
    lecturer: "Ms. Astha Sharma",
    block: "UK",
    room: "Lab - Oxford",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C1",
    day: "Fri",
    time: "08:00 AM - 09:00 AM",
    type: "Tutorial",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Nepal",
    room: "TR06 - Annapurna",
  },
  {
    year: "Year 2",
    faculty: "Networking",
    section: "C13",
    day: "Fri",
    time: "08:30 AM - 10:00 AM",
    type: "Lab",
    module: "Network Operating Systems",
    lecturer: "Mr. Rupsan Shrestha",
    block: "Skill Lab",
    room: "04 - Prajwol Adhikari",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C14",
    day: "Fri",
    time: "08:30 AM - 09:30 AM",
    type: "Tutorial",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Jaganath Paudyal",
    block: "London",
    room: "LT01 - Buckingham Palace",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C11",
    day: "Fri",
    time: "09:00 AM - 10:00 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Ujal Bhatta",
    block: "UK",
    room: "Lab - Newcastle",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Fri",
    time: "09:00 AM - 10:00 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Ishan Singh Thakuri",
    block: "Nepal",
    room: "TR06 - Annapurna",
  },
  {
    year: "Year 2",
    faculty: "Networking",
    section: "C5",
    day: "Fri",
    time: "09:00 AM - 10:30 AM",
    type: "Lab",
    module: "Network Operating Systems",
    lecturer: "Mr. Bishnu Pandey",
    block: "Skill Lab",
    room: "01 - Sarun Dahal",
  },
  {
    year: "Year 2",
    faculty: "Networking",
    section: "C3",
    day: "Fri",
    time: "09:00 AM - 10:00 AM",
    type: "Tutorial",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Alumni",
    room: "SR08 - Sajiya Gurung",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C2",
    day: "Fri",
    time: "09:00 AM - 10:00 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Mukesh Regmi",
    block: "Nepal",
    room: "TR03 - Pokhara",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C7",
    day: "Fri",
    time: "09:30 AM - 10:30 AM",
    type: "Tutorial",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Ayush Bhakta Pradhanang",
    block: "UK",
    room: "Lab - Oxford",
  },
  {
    year: "Year 2",
    faculty: "Networking",
    section: "C15",
    day: "Fri",
    time: "10:00 AM - 11:00 AM",
    type: "Tutorial",
    module: "Network Operating Systems",
    lecturer: "Mr. Rupsan Shrestha",
    block: "London",
    room: "SR01 - Tower Bridge",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C14",
    day: "Fri",
    time: "10:00 AM - 11:00 AM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Ishan Singh Thakuri",
    block: "Nepal",
    room: "TR06 - Annapurna",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C18",
    day: "Fri",
    time: "10:00 AM - 11:00 AM",
    type: "Tutorial",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Jaganath Paudyal",
    block: "Alumni",
    room: "LT08 - Naresh Lamgade",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C13",
    day: "Fri",
    time: "10:00 AM - 11:00 AM",
    type: "Tutorial",
    module: "Databases",
    lecturer: "Ms. Shresha Rajbhandari",
    block: "Alumni",
    room: "SR09 - Simran Bhattarai",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C4",
    day: "Fri",
    time: "10:00 AM - 11:00 AM",
    type: "Tutorial",
    module: "Databases",
    lecturer: "Ms. Astha Sharma",
    block: "Alumni",
    room: "SR10 - Samir Gautam",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C16",
    day: "Fri",
    time: "10:00 AM - 11:00 AM",
    type: "Tutorial",
    module: "Databases",
    lecturer: "Mr. Dipesh Raj Adhikari",
    block: "Nepal",
    room: "TR05 - Machapuchare",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C2",
    day: "Fri",
    time: "10:00 AM - 11:00 AM",
    type: "Tutorial",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Sugat Man Shakya",
    block: "Nepal",
    room: "TR07 - Kanchanjunga",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C9",
    day: "Fri",
    time: "10:30 AM - 11:30 AM",
    type: "Tutorial",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Ayush Bhakta Pradhanang",
    block: "UK",
    room: "Lab - Oxford",
  },
  {
    year: "Year 2",
    faculty: "Networking",
    section: "C6",
    day: "Fri",
    time: "10:30 AM - 12:00 PM",
    type: "Lab",
    module: "Network Operating Systems",
    lecturer: "Mr. Bishnu Pandey",
    block: "Skill Lab",
    room: "01 - Sarun Dahal",
  },
  {
    year: "Year 2",
    faculty: "Networking",
    section: "C4",
    day: "Fri",
    time: "11:00 AM - 12:00 PM",
    type: "Tutorial",
    module: "Network Operating Systems",
    lecturer: "Mr. Dipeshor Silwal",
    block: "Alumni",
    room: "SR07 - Sujan Khadgi",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C14",
    day: "Fri",
    time: "11:00 AM - 12:00 PM",
    type: "Tutorial",
    module: "Databases",
    lecturer: "Ms. Shresha Rajbhandari",
    block: "Alumni",
    room: "SR09 - Simran Bhattarai",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C5",
    day: "Fri",
    time: "11:00 AM - 12:00 PM",
    type: "Tutorial",
    module: "Databases",
    lecturer: "Ms. Astha Sharma",
    block: "Alumni",
    room: "SR10 - Samir Gautam",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C18",
    day: "Fri",
    time: "11:00 AM - 12:30 PM",
    type: "Tutorial",
    module: "Software Engineering",
    lecturer: "Mr. Ishan Singh Thakuri",
    block: "Nepal",
    room: "TR01 - Kantipur",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C17",
    day: "Fri",
    time: "11:00 AM - 12:00 PM",
    type: "Tutorial",
    module: "Databases",
    lecturer: "Mr. Dipesh Raj Adhikari",
    block: "Nepal",
    room: "TR05 - Machapuchare",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C17",
    day: "Fri",
    time: "12:00 PM - 01:30 PM",
    type: "Lab",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Jaganath Paudyal",
    block: "Skill Lab",
    room: "01 - Sarun Dahal",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C15",
    day: "Fri",
    time: "12:00 PM - 01:00 PM",
    type: "Tutorial",
    module: "Databases",
    lecturer: "Ms. Shresha Rajbhandari",
    block: "Alumni",
    room: "SR09 - Simran Bhattarai",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C6",
    day: "Fri",
    time: "12:00 PM - 01:00 PM",
    type: "Tutorial",
    module: "Databases",
    lecturer: "Ms. Astha Sharma",
    block: "Alumni",
    room: "SR10 - Samir Gautam",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C12",
    day: "Fri",
    time: "01:30 PM - 03:00 PM",
    type: "Lab",
    module: "Databases",
    lecturer: "Ms. Shresha Rajbhandari",
    block: "London",
    room: "SR04 - Tower of London",
  },
  {
    year: "Year 2",
    faculty: "Computing",
    section: "C15",
    day: "Fri",
    time: "02:00 PM - 03:00 PM",
    type: "Tutorial",
    module: "Cloud Computing and the Internet of Things",
    lecturer: "Mr. Jaganath Paudyal",
    block: "Alumni",
    room: "SR10 - Samir Gautam",
  },
];

// Helper function to return sections based on year and faculty
const getSections = (year, faculty) => {
  const sections = {
    "Year 1": {
      Computing: ["C11", "C12", "C13"],
      Networking: ["N11", "N12"],
      AI: ["AI11", "AI12"],
      Multimedia: ["M11", "M12", "M13"],
    },
    "Year 2": {
      Computing: [
        "C1",
        "C2",
        "C3",
        "C4",
        "C5",
        "C6",
        "C7",
        "C8",
        "C9",
        "C10",
        "C11",
        "C12",
        "C13",
        "C14",
        "C15",
        "C16",
        "C17",
        "C18",
      ],
      Networking: [
        "N1",
        "N2",
        "N3",
        "N4",
        "N5",
        "N6",
        "N7",
        "N8",
        "N9",
        "N10",
        "N11",
      ],
      AI: ["AI1", "AI2", "AI3", "AI4", "AI5", "AI6"],
      Multimedia: ["M1", "M2", "M3", "M4", "M5", "M6"],
    },
    "Year 3": {
      Computing: ["C31", "C32", "C33"],
      Networking: ["N31", "N32"],
      AI: ["AI31", "AI32"],
      Multimedia: ["M31", "M32", "M33"],
    },
  };

  return sections[year][faculty] || [];
};

const TodayPage = () => {
  // Initial day based on the current date
  const getCurrentDay = () => {
    const days = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri"];
    const todayIndex = new Date().getDay();
    return days[todayIndex];
  };

  // State for dropdowns and selections
  const [showDayDropdown, setShowDayDropdown] = useState(false);
  const [showPopup, setShowPopup] = useState(false);
  const [selectedDay, setSelectedDay] = useState(getCurrentDay());
  const [selectedYear, setSelectedYear] = useState("Year 2");
  const [selectedFaculty, setSelectedFaculty] = useState("Computing");
  const [selectedSection, setSelectedSection] = useState("C12");
  const [displayOptions, setDisplayOptions] = useState({
    time: true,
    block: true,
    room: true,
    classType: false,
    moduleTitle: false,
    lecturer: false,
  });

  const dayDropdownRef = useRef(null);
  const popupRef = useRef(null);

  // Toggle visibility for choose options and day dropdown
  const handleChooseClick = () => setShowPopup((prev) => !prev);
  const handleDayButtonClick = () => setShowDayDropdown(!showDayDropdown);

  // Handle selection changes
  const handleCheckboxChange = (event) => {
    setDisplayOptions({
      ...displayOptions,
      [event.target.name]: event.target.checked,
    });
  };

  const handleDayChange = (day) => {
    setSelectedDay(day);
    setShowDayDropdown(false);
  };

  useEffect(() => {
    const handleClickOutside = (event) => {
      if (
        showPopup &&
        popupRef.current &&
        !popupRef.current.contains(event.target) &&
        !event.target.closest(".choose-btn")
      ) {
        setShowPopup(false);
      }
      if (
        showDayDropdown &&
        dayDropdownRef.current &&
        !dayDropdownRef.current.contains(event.target)
      ) {
        setShowDayDropdown(false);
      }
    };

    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [showPopup, showDayDropdown]);

  return (
    <div className="bg-white text-[#41448B] pt-28 min-h-screen flex flex-col items-center">
      <h1 className="text-2xl font-bold text-center mb-4">Today's Routine</h1>

      {/* Year, Faculty, Section dropdowns */}
      <div className="flex justify-center space-x-4 mb-8">
        {/* Year Dropdown */}
        <select
          value={selectedYear}
          onChange={(e) => setSelectedYear(e.target.value)}
          className="p-2 bg-[#41448B] text-white hover:bg-[#5a5f99] border border-gray-300 rounded-md"
        >
          <option className="bg-white text-[#41448B]" value="Year 1">
            Year 1
          </option>
          <option className="bg-white text-[#41448B]" value="Year 2">
            Year 2
          </option>
          <option className="bg-white text-[#41448B]" value="Year 3">
            Year 3
          </option>
        </select>

        {/* Faculty Dropdown */}
        <select
          value={selectedFaculty}
          onChange={(e) => setSelectedFaculty(e.target.value)}
          className="p-2 bg-[#41448B] text-white hover:bg-[#5a5f99] border border-gray-300 rounded-md"
        >
          <option className="bg-white text-[#41448B]" value="Computing">
            Computing
          </option>
          <option className="bg-white text-[#41448B]" value="Networking">
            Networking
          </option>
          <option className="bg-white text-[#41448B]" value="AI">
            AI
          </option>
          <option className="bg-white text-[#41448B]" value="Multimedia">
            Multimedia
          </option>
        </select>

        {/* Section Dropdown */}
        <select
          value={selectedSection}
          onChange={(e) => setSelectedSection(e.target.value)}
          className="p-2 bg-[#41448B] text-white hover:bg-[#5a5f99] border border-gray-300 rounded-md"
        >
          {getSections(selectedYear, selectedFaculty).map((section) => (
            <option
              className="bg-white text-[#41448B]"
              key={section}
              value={section}
            >
              {section}
            </option>
          ))}
        </select>
      </div>

      {/* Day Selection Dropdown */}
      <div className="relative mb-8" ref={dayDropdownRef}>
        <button
          onClick={handleDayButtonClick}
          className="flex items-center p-2 bg-[#41448B] hover:bg-[#5a5f99] hover:text-white text-white rounded-md transition duration-300 day-btn"
        >
          <span className="mr-2">Select Day</span>
          <FaChevronDown />
        </button>
        {showDayDropdown && (
          <div className="dropdown-menu bg-white text-[#41448B] p-2 mt-2 rounded-md shadow-lg absolute top-full left-0 w-28 z-50">
            {["Sun", "Mon", "Tue", "Wed", "Thu", "Fri"].map((day) => (
              <div
                key={day}
                className={`py-1 px-2 cursor-pointer hover:bg-[#f0f0f0] ${
                  selectedDay === day ? "bg-[#e0e0e0]" : ""
                }`}
                onClick={() => handleDayChange(day)}
              >
                {day}
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Choose Button for Display Options */}
      <div className="relative mb-8">
        <button
          onClick={handleChooseClick}
          className="flex items-center p-2 bg-[#41448B] hover:bg-[#5a5f99] hover:text-white text-white rounded-md transition duration-300 choose-btn"
        >
          Choose Options <AiFillCaretDown className="ml-2" />
        </button>

        {/* Popup Menu with Checkboxes */}
        {showPopup && (
          <div
            ref={popupRef}
            className="popup-menu bg-white text-[#41448B] p-2 mt-2 rounded-md shadow-lg absolute top-full left-0 w-40 z-50 text-sm"
          >
            <div className="flex flex-col">
              <label className="flex items-center mb-1">
                <input
                  type="checkbox"
                  name="time"
                  checked={displayOptions.time}
                  onChange={handleCheckboxChange}
                  className="mr-2"
                />
                Time
              </label>
              <label className="flex items-center mb-1">
                <input
                  type="checkbox"
                  name="block"
                  checked={displayOptions.block}
                  onChange={handleCheckboxChange}
                  className="mr-2"
                />
                Block
              </label>
              <label className="flex items-center mb-1">
                <input
                  type="checkbox"
                  name="room"
                  checked={displayOptions.room}
                  onChange={handleCheckboxChange}
                  className="mr-2"
                />
                Room
              </label>
              <label className="flex items-center mb-1">
                <input
                  type="checkbox"
                  name="classType"
                  checked={displayOptions.classType}
                  onChange={handleCheckboxChange}
                  className="mr-2"
                />
                Class Type
              </label>
              <label className="flex items-center mb-1">
                <input
                  type="checkbox"
                  name="moduleTitle"
                  checked={displayOptions.moduleTitle}
                  onChange={handleCheckboxChange}
                  className="mr-2"
                />
                Module Title
              </label>
              <label className="flex items-center mb-1">
                <input
                  type="checkbox"
                  name="lecturer"
                  checked={displayOptions.lecturer}
                  onChange={handleCheckboxChange}
                  className="mr-2"
                />
                Lecturer
              </label>
            </div>
          </div>
        )}
      </div>

      {/* Routine Table */}
      <div className="w-full flex justify-center">
        <table className="table-auto text-left border-collapse border border-gray-300 w-3/4">
          <thead>
            <tr className="bg-[#41448B] text-white">
              {displayOptions.time && (
                <th className="border border-gray-300 px-4 py-2">Time</th>
              )}
              {displayOptions.block && (
                <th className="border border-gray-300 px-4 py-2">Block</th>
              )}
              {displayOptions.room && (
                <th className="border border-gray-300 px-4 py-2">Room</th>
              )}
              {displayOptions.classType && (
                <th className="border border-gray-300 px-4 py-2">Type</th>
              )}
              {displayOptions.moduleTitle && (
                <th className="border border-gray-300 px-4 py-2">Module</th>
              )}
              {displayOptions.lecturer && (
                <th className="border border-gray-300 px-4 py-2">Lecturer</th>
              )}
            </tr>
          </thead>
          <tbody>
            {routineData
              .filter(
                (entry) =>
                  entry.year === selectedYear &&
                  entry.faculty === selectedFaculty &&
                  entry.section === selectedSection &&
                  entry.day === selectedDay
              )
              .map((entry, index) => (
                <tr key={index}>
                  {displayOptions.time && (
                    <td className="border border-gray-300 px-4 py-2">
                      {entry.time}
                    </td>
                  )}
                  {displayOptions.block && (
                    <td className="border border-gray-300 px-4 py-2">
                      {entry.block}
                    </td>
                  )}
                  {displayOptions.room && (
                    <td className="border border-gray-300 px-4 py-2">
                      {entry.room}
                    </td>
                  )}
                  {displayOptions.classType && (
                    <td className="border border-gray-300 px-4 py-2">
                      {entry.type}
                    </td>
                  )}
                  {displayOptions.moduleTitle && (
                    <td className="border border-gray-300 px-4 py-2">
                      {entry.module}
                    </td>
                  )}
                  {displayOptions.lecturer && (
                    <td className="border border-gray-300 px-4 py-2">
                      {entry.lecturer}
                    </td>
                  )}
                </tr>
              ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default TodayPage;
